### ISSUE TITLE
2019 Giveaway URLs

### ISSUE THREAD

**Issue by RelativePrime** [BAG-OF-CHIPS-XX/HGTV-_Home_Giveaway_Sweepstakes#1]
The urls for the 2019 submission pages seem a bit more obfuscated. I dug through page elements, but failed to extract ones which are working. Might you have any suggestions?

Cheers, and thanks for the script.

**Comment by BAG-OF-CHIPS-XX** [comment]
Look for iframes, most content seems to be inside an iframe.

**Comment by santatrout** [comment]
I just tried this out today for the current contest and these worked for me.

HGTV_URL = 'https://www.hgtv.com/design/hgtv-smart-home/sweepstakes'
DIY_URL = 'https://www.diynetwork.com/hgtv-smart-home?ocid=xp:SH19_Sweeps_News_Page'
